### ISSUE TITLE
Meta issue for payload autocompletion bugs

### ISSUE THREAD

**Issue by ywangd** [ywangd/peek#150]
- [x] Completion for match field
```
GET _search
{
  "query": {
    "match": {
      "content": {
        ""  // <-- no completion here, but should
      }
    }
  }
}
```

- [x] Completion inside highlight
```
GET _search
{
  "highlight": {
    ""  // <-- no completion available, but should
  },
}
```

- [x] The `FIELD` placeholder should match arbitrary fields

- [x] `__any_of` not handled
```
POST _aliases
{
  "actions": [
    {
      ""  // <-- __any_of appears here, but should be handled
    }
  ],
}
```

- [x] nested field not handled
```
PUT index
{
  "mappings": {
    "properties": {
      "tags": {
        "type": "text",
        "fields": {
          "keyword": {
            "I"  // <-- should have "type" as candidate here, but shows "properties". Kibana Console shows nothing!
          }
        }
      }
    }
  }
}
```

- [x] No completion available for _delete_by_query. Funny that _update_by has it
